# Generated by Django 2.1.8 on 2019-04-25 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='이메일 형식에 맞지 않습니다.')]),
        ),
    ]
